New yeoda filename
TUW-GEO/geopathfinder pull request #21
Opened 2020-10-07 14:00 UTC by fl0roth

Implementation of the new filename and folder logic with a more compact and general purpose use. The corresponding changes include:
- Introduction of a yeoda_naming class which represents the new filenaming and folder logic and a corresponding test_yeoda_naming routine. 
- Introduction of fields with variable length (defined by length = 0) in the SmartFilename and SmartFilenamePart class.
- Introduction of an option (input parameter "compact") to use a compact filename design. If it is set to True, empty fields are represented by a single pad character and all fields are treated with variable length.  
- Adaption of the attached conda environment by updating the python-dateuntil modul (issue#18).

2020-10-19 16:21 UTC, bbauerma approved these changes
Looks fine for me.
a) yeoda-filename works as expected
b) all tests on my local Windows machine are green

2020-10-21 07:59 UTC, FelixReuss approved these changes
- works fine with S1 Sigma

2020-10-21 11:56 UTC, cnavacch requested changes
Looks very good! Three changes still need to be done:

1. Fixing Python version (@bbauerma @fl0roth ?)
2. Change loop in `_build_fn()` (I will do this).
3. Add `compact=False` in the `__init__` of all other file naming conventions. This might me a nice feature to have for the existing file naming conventions (@fl0roth ).

2020-10-21 11:56 UTC, cnavacch commented on src/geopathfinder/file_naming.py
> +                filename = filename[:-len(fn_parts[i-1])] + (fn_parts[i-1] + fn_parts[i])
That part can be made shorter, I will fix this, because this was originally implemented by myself.

2020-10-21 14:38 UTC, bbauerma commented on conda_env.yml
> +  - python
actually, can we remove python at all?

2020-10-21 14:39 UTC, bbauerma commented on conda_env.yml
> +  - python
it should work for python 3. for all python 3 versions (3.6, 3.7,..)

2020-10-21 15:18 UTC, sebhahn commented on conda_env.yml
> +  - python
I would recommend >= 3.6

2020-10-22 07:21 UTC, cnavacch commented on conda_env.yml
> +  - python
The issue I see at the moment is that we use the same conda yml file for Travis. I prefer to have separate yml files for testing each Python version with Travis. This ensures that each Python version works/is supported and is always tested and makes it easier to reset package dependencies for a specific Python version. In the main yml file I agree with @sebhahn , there we could set `python >= 3.6`.

2020-10-22 07:53 UTC, bbauerma commented on conda_env.yml
> +  - python
is already set to python >= 3.6 now
please proceed and implement the steps you suggested - i want to release a new version...

2020-10-23 16:41 UTC, cnavacch approved these changes
Great, all changes are fine from my side!

2020-10-28 17:17 UTC, merged