added "creator" as last filename part in the yeoda_filenaming
TUW-GEO/geopathfinder pull request #30
Opened 2022-04-13 11:44 UTC by bbauerma

added "creator" as last filename part in the yeoda_filenaming & SmartFilename allows now empty last entry

2022-04-14 08:09 UTC, fl0roth commented
I have tested the changes and everything works fine so far. Would it be useful to do the same approach for the first field as well,  although there is currently no naming convention which makes use of it?

2022-04-14 08:09 UTC, fl0roth approved these changes

2022-04-19 21:05 UTC, cnavacch requested changes
Looks good! I have only one minor comment, which could be addressed, but I would rather consider it to be optional.

2022-04-26 08:56 UTC, cnavacch approved these changes

2022-04-26 08:57 UTC, cnavacch commented
@bbauerma Please do a final check if you are happy with the changes I've implemented. All tests work on my side.

2022-04-27 12:47 UTC, merged